version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - chat-network

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - chat-network

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    depends_on:
      - server
    networks:
      - chat-network
    stdin_open: true
    tty: true

networks:
  chat-network:
    driver: bridge
